In [1]:
import pandas as pd
import numpy as np
import preprocessing

In [2]:
data = pd.read_csv('car_price_prediction.csv')
data.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [3]:
data = preprocessing.preprocessing_pipeline(data)

Preprocessing started...
Initial shape: (19237, 18)
After dropping duplicates: (18924, 18)
Replacing categorical values...
After cleaning outliers: (16037, 18)
Feature engineering...
Dropping columns...
Final shape: (16037, 16)

In [4]:
data.head()

,Price,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags,Age
0,13328,1399,LEXUS,RX 450,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,Left wheel,Silver,12,16
1,16621,1018,CHEVROLET,Equinox,Jeep,No,Petrol,3.0,192000,6.0,Tiptronic,4x4,Left wheel,Black,8,15
2,8467,0,HONDA,FIT,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,Right-hand drive,Black,2,20
3,3607,862,FORD,Escape,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,Left wheel,White,0,15
4,11726,446,HONDA,FIT,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,Left wheel,Silver,4,12

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# hot encoding
one_hot_columns=['Leather interior', 'Gear box type', 'Drive wheels', 'Wheel']
# data=pd.get_dummies(data,columns=one_hot_columns)
oh_encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
oh_encoded_train=oh_encoder.fit_transform(data[one_hot_columns])
oh_encoded_columns=oh_encoder.get_feature_names_out(one_hot_columns)

In [6]:
oh_encoded_columns

array(['Leather interior_No', 'Leather interior_Yes',
       'Gear box type_Automatic', 'Gear box type_Manual',
       'Gear box type_Tiptronic', 'Gear box type_Variator',
       'Drive wheels_4x4', 'Drive wheels_Front', 'Drive wheels_Rear',
       'Wheel_Left wheel', 'Wheel_Right-hand drive'], dtype=object)

In [7]:
oh_encoded_train

array([[0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.]])

In [8]:
oh_encoded_tarin_df=pd.DataFrame(oh_encoded_train,columns=oh_encoded_columns,index=data.index)
oh_encoded_tarin_df

,Leather interior_No,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
19232,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19233,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
19234,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19235,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19236,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [9]:
# to get original data
data=pd.concat([data,oh_encoded_tarin_df],axis=1)
# data after encoding
data.drop(columns=one_hot_columns,inplace=True)

In [ ]:
# save the hot encodes for future use
with open('','') as f:

In [10]:
data

,Price,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,13328,1399,LEXUS,RX 450,Jeep,Hybrid,3.5,186005,6.0,Silver,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,16621,1018,CHEVROLET,Equinox,Jeep,Petrol,3.0,192000,6.0,Black,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,8467,0,HONDA,FIT,Hatchback,Petrol,1.3,200000,4.0,Black,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,3607,862,FORD,Escape,Jeep,Hybrid,2.5,168966,4.0,White,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,11726,446,HONDA,FIT,Hatchback,Petrol,1.3,91901,4.0,Silver,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0,MERCEDES-BENZ,CLK 200,Coupe,CNG,2.0,300000,4.0,Silver,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19233,15681,831,HYUNDAI,Sonata,Sedan,Petrol,2.4,161600,4.0,Red,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
19234,26108,836,HYUNDAI,Tucson,Jeep,Diesel,2.0,116365,4.0,Grey,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19235,5331,1288,CHEVROLET,Captiva,Jeep,Diesel,2.0,51258,4.0,Black,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19236,470,753,HYUNDAI,Sonata,Sedan,Hybrid,2.4,186923,4.0,White,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [11]:
# encoding all columns
label_encode_columns=['Manufacturer', 'Model', 'Category', 'Fuel type', 'Color']

label_encoders={} # this dictionary contains all label encodres after fit

for col in label_encode_columns:
    label_encoder=LabelEncoder()
    data[col]=label_encoder.fit_transform(data[col])
    label_encoders[col]=label_encoder

In [12]:
label_encoders

{'Manufacturer': LabelEncoder(),
 'Model': LabelEncoder(),
 'Category': LabelEncoder(),
 'Fuel type': LabelEncoder(),
 'Color': LabelEncoder()}

In [26]:
# save the label encoders for future use
with open('label_encoders.pkl','wb') as f:
    pickle.dump(label_encoders,f)

In [13]:
data

,Price,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,13328,1399,28,1037,4,2,3.5,186005,6.0,12,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,16621,1018,6,563,4,5,3.0,192000,6.0,1,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,8467,0,18,585,3,5,1.3,200000,4.0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,3607,862,13,565,4,2,2.5,168966,4.0,14,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,11726,446,18,585,3,5,1.3,91901,4.0,12,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0,32,325,1,0,2.0,300000,4.0,12,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19233,15681,831,20,1101,9,5,2.4,161600,4.0,11,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
19234,26108,836,20,1200,4,1,2.0,116365,4.0,7,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19235,5331,1288,6,387,4,1,2.0,51258,4.0,1,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19236,470,753,20,1101,9,2,2.4,186923,4.0,14,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [14]:
X=data.drop('Price',axis=1)
y=data['Price']

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,shuffle=True,random_state=42)

print(f"Train set: {X_train.shape} samples")
print(f"Test set: {X_test.shape} samples")

Train set: (13631, 22) samples
Test set: (2406, 22) samples

In [16]:
from sklearn.discriminant_analysis import StandardScaler

numerical_columns = ['Levy', 'Engine volume', 'Mileage', 'Age']

scaler = StandardScaler()
X_train[numerical_columns]= scaler.fit_transform(X_train[numerical_columns])
X_test[numerical_columns] = scaler.transform(X_test[numerical_columns])

In [23]:
import pickle
# save the scaler
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [17]:
data

,Price,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,13328,1399,28,1037,4,2,3.5,186005,6.0,12,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,16621,1018,6,563,4,5,3.0,192000,6.0,1,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,8467,0,18,585,3,5,1.3,200000,4.0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,3607,862,13,565,4,2,2.5,168966,4.0,14,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,11726,446,18,585,3,5,1.3,91901,4.0,12,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0,32,325,1,0,2.0,300000,4.0,12,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19233,15681,831,20,1101,9,5,2.4,161600,4.0,11,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
19234,26108,836,20,1200,4,1,2.0,116365,4.0,7,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19235,5331,1288,6,387,4,1,2.0,51258,4.0,1,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19236,470,753,20,1101,9,2,2.4,186923,4.0,14,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error,r2_score

rf= RandomForestRegressor()
rf.fit(X_train,y_train)

y_test_pred = rf.predict(X_test)
rmse = root_mean_squared_error(y_test,y_test_pred)
r2 = r2_score(y_test,y_test_pred)

print(f"Root Mean Squared Error with RandomForestRegressor algorythm: {rmse}")
print(f"R^2 Score RandomForestRegressor algorythm: {r2}")

Root Mean Squared Error with RandomForestRegressor algorythm: 5373.269696598064
R^2 Score RandomForestRegressor algorythm: 0.778480723260127

In [22]:
# save the model for future use 
with open('randomForestModel.pkl','wb') as f:
    pickle.dump(rf,f)